# Nome da aplicacao
spring.application.name=raizes-backend
# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/raizes_db
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
# Swagger
springdoc.swagger-ui.path=/swagger-ui.html
# JWT
jwt.secret=raizes-nordeste-chave-secreta-super-longa-2026
jwt.expiration=86400000